/**
 * PAGE CONTENT CONFIG
 * 以后补充项目名、作者、链接、视频和指标，主要修改这个文件即可。
 * 所有本地路径都使用相对地址，以兼容 GitHub Pages 的子目录部署。
 */
window.PROJECT_DATA = {
  project: {
    shortName: "TBDub",
    kicker: "TECHNICAL REPORT · SEPTEMBER 2026",
    titleEn: "Production-Oriented Visual Dubbing",
    titleCn: "面向生产的视觉配音",
    affiliation: "TaoLive AIGC · Alibaba Group",
    abstract:
      "视觉配音需要在使用替换语音驱动口部运动的同时，保持人物身份、外观与时序一致性。TBDub 在 X-Dub 的无显式口部遮罩视频编辑框架上进行面向生产的任务自适应后训练，通过生产域数据、条件端增强、同身份口部先验和多层 HuBERT 语音特征得到 30 步 Teacher；随后将 DMD/DMD2 适配到条件视频编辑，蒸馏得到 2 步 Student。在 38 个 TalkVid 样本上，Teacher 相比 X-Dub 全面改善所报告的重建、感知、身份与同步指标；Student 基本保持 Teacher 的视觉质量和音画同步，并在单张 NVIDIA H20、512×512 的 VAE-to-VAE 核心生成链路上达到 7.13 FPS。",
    summaryIntro:
      "TBDub 面向直播、棚拍与 AIGC 生成视频中的实际失效模式，将生产域后训练和任务感知少步蒸馏连接为一条完整链路，在身份与唇齿细节、时序稳定性、困难场景鲁棒性和推理效率之间取得更适合部署的平衡。",
    focusAreas: [
      {
        index: "01",
        title: "Identity & Detail Fidelity",
        titleCn: "身份与精细结构保持",
        text: "保持嘴唇颜色、牙齿形状、皮肤纹理与眼部细节，抑制局部重绘以及长序列生成中的身份、颜色和锐度漂移。",
      },
      {
        index: "02",
        title: "Long-range Temporal Stability",
        titleCn: "长时序稳定性",
        text: "增强跨帧外观与结构一致性，减少人脸和唇部的光照闪烁、牙齿粘连与尺度波动，以及随推理长度增长而累积的外观退化。",
      },
      {
        index: "03",
        title: "Robust Visual Editing",
        titleCn: "复杂场景鲁棒性",
        text: "面向遮挡、大角度头部偏转、快速头动与运动模糊保持稳定编辑，降低口部覆盖错误、边界伪影和局部生成异常。",
      },
      {
        index: "04",
        title: "Cross-driven & Cross-domain",
        titleCn: "跨音频与跨域泛化",
        text: "在驱动音频与原始口型不匹配，以及 AIGC 生产视频等域外条件下，提高音素—口型对应准确度、唇齿清晰度与画面融合自然度。",
      },
      {
        index: "05",
        title: "Task-aware Few-step Distillation",
        titleCn: "任务感知的少步蒸馏",
        text: "以 X-Dub 的三路动态 CFG 构造 guided Teacher score，通过条件分布匹配将 30 步 Teacher 蒸馏为每步单路前向的 2 步 Student。",
      },
    ],
    demoIntro:
      "定性结果覆盖多语种同源重建、MiniMax H3 生成视频重绘，以及大姿态、遮挡、快速头动和随机真实视频上的跨音频驱动。视频比单帧截图更能反映同步、口腔细节与时序稳定性。",
    authors: [
      { name: "Bihan Li", note: "*" },
      { name: "Xinyang Li", note: "*" },
      { name: "Zeran Xu", note: "" },
      { name: "Meiguang Jin", note: "†" },
      { name: "Junfeng Ma", note: "" },
    ],
    authorNote: "* 共同一作　† 通讯作者",
    links: {
      paper: "https://live-aigc-dh-cloud.oss-cn-zhangjiakou.aliyuncs.com/qifu/tmp/oss_cp/main_20260905_221343.pdf",
      code: "https://github.com/TaoLiveAIGC/TBDub",
      model: "https://huggingface.co/TaoLiveAIGC/TBDub",
    },
  },

  resultSettings: [
    {
      id: "self",
      index: "A",
      title: "Self-driven Reconstruction",
      titleCn: "同源音频重建",
      description: "使用目标视频自身的音频驱动同一身份，重点评估画面重建质量、身份保持、唇形同步和时序稳定性。",
      subgroups: [
        {
          id: "multilingual",
          index: "A1",
          title: "Multilingual Evaluation",
          titleCn: "多语种测试",
          description: "在中文、英文、韩语、俄语和日语视频上评估同源音频重建效果。",
        },
        {
          id: "aigc-video",
          index: "A2",
          title: "AIGC-generated Video Evaluation",
          titleCn: "AIGC 生成视频测试",
          description: "使用 MiniMax H3 同时生成视频和音频，再用配套生成音频重绘生成视频，评估二次视觉配音对 AIGC 内容域及已有口部缺陷的适应性。",
          emptyText: "AIGC-generated video samples will be added here.",
        },
      ],
    },
    {
      id: "cross",
      index: "B",
      title: "Cross-driven Lip Synchronization",
      titleCn: "跨音频唇形同步",
      description: "使用替换音频重绘目标人物口型，重点评估目标音素与源视频面部动态不匹配时的口型响应，以及面对姿态、遮挡和随机真实场景时的泛化能力。",
      subgroups: [
        {
          id: "large-pose",
          index: "B1",
          title: "Large-pose Evaluation",
          titleCn: "大角度姿态测试",
          description: "测试模型面对大角度侧脸、转头和显著姿态变化时的口型同步稳定性。",
        },
        {
          id: "occlusion",
          index: "B2",
          title: "Occlusion Evaluation",
          titleCn: "遮挡测试",
          description: "测试嘴部或面部被手部、物体等遮挡时的重绘质量与时序稳定性。",
        },
        {
          id: "rapid-head-motion",
          index: "B3",
          title: "Rapid Head-motion Evaluation",
          titleCn: "快速头动测试",
          description: "测试快速转头、抖动和剧烈头部运动等困难条件下的模型鲁棒性。",
        },
        {
          id: "in-the-wild",
          index: "B4",
          title: "In-the-wild Evaluation",
          titleCn: "随机真实视频测试",
          description: "在多人物、多场景和多种拍摄条件的随机真实视频上评估泛化能力。",
        },
      ],
    },
  ],

  qualitativeResults: [
    {
      id: "self-01",
      setting: "self",
      subgroup: "multilingual",
      scenario: "",
      title: "Chinese",
      description: "中文同源音频重建：输入视频与驱动音频来自同一段真实视频，可与 Ground Truth 进行直接对照。",
      tags: ["Same identity", "Chinese", "Ground truth available"],
      methods: [
        { label: "Input", src: "./assets/videos/comparisons/self-driven/chinese/sample1-input.mp4", poster: "" },
        { label: "TBDub", src: "./assets/videos/comparisons/self-driven/chinese/sample1-ours.mp4", poster: "", highlight: true },
        { label: "TBDub (2-step)", src: "./assets/videos/comparisons/self-driven/chinese/sample1-ours-2step.mp4", poster: "", highlight: true },
        { label: "X-Dub", src: "./assets/videos/comparisons/self-driven/chinese/sample1-xdub.mp4", poster: "" },
        { label: "LipForcing", src: "./assets/videos/comparisons/self-driven/chinese/sample1-lipforcing.mp4", poster: "" },
        { label: "KeySync", src: "./assets/videos/comparisons/self-driven/chinese/sample1-keysync.mp4", poster: "" },
        { label: "LatentSync", src: "./assets/videos/comparisons/self-driven/chinese/sample1-latentsync.mp4", poster: "" },
      ],
    },
    {
      id: "self-english-01",
      setting: "self",
      subgroup: "multilingual",
      scenario: "",
      title: "English",
      description: "英文同源音频重建：输入视频与驱动音频来自同一段真实视频，可与 Ground Truth 进行直接对照。",
      tags: ["Same identity", "English", "Ground truth available"],
      methods: [
        { label: "Input", src: "./assets/videos/comparisons/self-driven/english/sample1-input.mp4", poster: "" },
        { label: "TBDub", src: "./assets/videos/comparisons/self-driven/english/sample1-ours.mp4", poster: "", highlight: true },
        { label: "TBDub (2-step)", src: "./assets/videos/comparisons/self-driven/english/sample1-ours-2step.mp4", poster: "", highlight: true },
        { label: "X-Dub", src: "./assets/videos/comparisons/self-driven/english/sample1-xdub.mp4", poster: "" },
        { label: "LipForcing", src: "./assets/videos/comparisons/self-driven/english/sample1-lipforcing.mp4", poster: "" },
        { label: "KeySync", src: "./assets/videos/comparisons/self-driven/english/sample1-keysync.mp4", poster: "" },
        { label: "LatentSync", src: "./assets/videos/comparisons/self-driven/english/sample1-latentsync.mp4", poster: "" },
      ],
    },
    {
      id: "self-korean-01",
      setting: "self",
      subgroup: "multilingual",
      scenario: "",
      title: "Korean",
      description: "韩语同源音频重建：输入视频与驱动音频来自同一段真实视频，可与 Ground Truth 进行直接对照。",
      tags: ["Same identity", "Korean", "Ground truth available"],
      methods: [
        { label: "Input", src: "./assets/videos/comparisons/self-driven/korean/sample1-input.mp4", poster: "" },
        { label: "TBDub", src: "./assets/videos/comparisons/self-driven/korean/sample1-ours.mp4", poster: "", highlight: true },
        { label: "TBDub (2-step)", src: "./assets/videos/comparisons/self-driven/korean/sample1-ours-2step.mp4", poster: "", highlight: true },
        { label: "X-Dub", src: "./assets/videos/comparisons/self-driven/korean/sample1-xdub.mp4", poster: "" },
        { label: "LipForcing", src: "./assets/videos/comparisons/self-driven/korean/sample1-lipforcing.mp4", poster: "" },
        { label: "KeySync", src: "./assets/videos/comparisons/self-driven/korean/sample1-keysync.mp4", poster: "" },
        { label: "LatentSync", src: "./assets/videos/comparisons/self-driven/korean/sample1-latentsync.mp4", poster: "" },
      ],
    },
    {
      id: "self-russian-01",
      setting: "self",
      subgroup: "multilingual",
      scenario: "",
      title: "Russian",
      description: "俄语同源音频重建：输入视频与驱动音频来自同一段真实视频，可与 Ground Truth 进行直接对照。",
      tags: ["Same identity", "Russian", "Ground truth available"],
      methods: [
        { label: "Input", src: "./assets/videos/comparisons/self-driven/russian/sample1-input.mp4", poster: "" },
        { label: "TBDub", src: "./assets/videos/comparisons/self-driven/russian/sample1-ours.mp4", poster: "", highlight: true },
        { label: "TBDub (2-step)", src: "./assets/videos/comparisons/self-driven/russian/sample1-ours-2step.mp4", poster: "", highlight: true },
        { label: "X-Dub", src: "./assets/videos/comparisons/self-driven/russian/sample1-xdub.mp4", poster: "" },
        { label: "LipForcing", src: "./assets/videos/comparisons/self-driven/russian/sample1-lipforcing.mp4", poster: "" },
        { label: "KeySync", src: "./assets/videos/comparisons/self-driven/russian/sample1-keysync.mp4", poster: "" },
        { label: "LatentSync", src: "./assets/videos/comparisons/self-driven/russian/sample1-latentsync.mp4", poster: "" },
      ],
    },
    {
      id: "self-japanese-01",
      setting: "self",
      subgroup: "multilingual",
      scenario: "",
      title: "Japanese",
      description: "日语同源音频重建：输入视频与驱动音频来自同一段真实视频，可与 Ground Truth 进行直接对照。",
      tags: ["Same identity", "Japanese", "Ground truth available"],
      methods: [
        { label: "Input", src: "./assets/videos/comparisons/self-driven/japanese/sample1-input.mp4", poster: "" },
        { label: "TBDub", src: "./assets/videos/comparisons/self-driven/japanese/sample1-ours.mp4", poster: "", highlight: true },
        { label: "TBDub (2-step)", src: "./assets/videos/comparisons/self-driven/japanese/sample1-ours-2step.mp4", poster: "", highlight: true },
        { label: "X-Dub", src: "./assets/videos/comparisons/self-driven/japanese/sample1-xdub.mp4", poster: "" },
        { label: "LipForcing", src: "./assets/videos/comparisons/self-driven/japanese/sample1-lipforcing.mp4", poster: "" },
        { label: "KeySync", src: "./assets/videos/comparisons/self-driven/japanese/sample1-keysync.mp4", poster: "" },
        { label: "LatentSync", src: "./assets/videos/comparisons/self-driven/japanese/sample1-latentsync.mp4", poster: "" },
      ],
    },
    {
      id: "self-aigc-01",
      setting: "self",
      subgroup: "aigc-video",
      scenario: "AIGC Video · Sample 1",
      title: "AIGC-generated video reconstruction · Sample 1",
      description: "面向 AIGC 生产视频的同源音频重建案例，用于评估模型对合成人像与生成画面的适应性。",
      tags: ["Same identity", "AIGC video", "Production content"],
      methods: [
        { label: "Input", src: "./assets/videos/comparisons/self-driven/aigc/sample1-input.mp4", poster: "" },
        { label: "TBDub", src: "./assets/videos/comparisons/self-driven/aigc/sample1-ours.mp4", poster: "", highlight: true },
        { label: "X-Dub", src: "./assets/videos/comparisons/self-driven/aigc/sample1-xdub.mp4", poster: "" },
        { label: "LipForcing", src: "./assets/videos/comparisons/self-driven/aigc/sample1-lipforcing.mp4", poster: "" },
        { label: "KeySync", src: "./assets/videos/comparisons/self-driven/aigc/sample1-keysync.mp4", poster: "" },
        { label: "LatentSync", src: "./assets/videos/comparisons/self-driven/aigc/sample1-latentsync.mp4", poster: "" },
      ],
    },
    {
      id: "self-aigc-02",
      setting: "self",
      subgroup: "aigc-video",
      scenario: "AIGC Video · Sample 2",
      title: "AIGC-generated video reconstruction · Sample 2",
      description: "面向直播间场景 AIGC 生产视频的同源音频重建案例。",
      tags: ["Same identity", "AIGC video", "Livestream room"],
      methods: [
        { label: "Input", src: "./assets/videos/comparisons/self-driven/aigc/sample2-input.mp4", poster: "" },
        { label: "TBDub", src: "./assets/videos/comparisons/self-driven/aigc/sample2-ours.mp4", poster: "", highlight: true },
        { label: "X-Dub", src: "./assets/videos/comparisons/self-driven/aigc/sample2-xdub.mp4", poster: "" },
        { label: "LipForcing", src: "./assets/videos/comparisons/self-driven/aigc/sample2-lipforcing.mp4", poster: "" },
        { label: "KeySync", src: "./assets/videos/comparisons/self-driven/aigc/sample2-keysync.mp4", poster: "" },
        { label: "LatentSync", src: "./assets/videos/comparisons/self-driven/aigc/sample2-latentsync.mp4", poster: "" },
      ],
    },
    {
      id: "self-aigc-03",
      setting: "self",
      subgroup: "aigc-video",
      scenario: "AIGC Video · Sample 3",
      title: "AIGC-generated video reconstruction · Sample 3",
      description: "面向办公室场景 AIGC 生产视频的同源音频重建案例。",
      tags: ["Same identity", "AIGC video", "Office"],
      methods: [
        { label: "Input", src: "./assets/videos/comparisons/self-driven/aigc/sample3-input.mp4", poster: "" },
        { label: "TBDub", src: "./assets/videos/comparisons/self-driven/aigc/sample3-ours.mp4", poster: "", highlight: true },
        { label: "X-Dub", src: "./assets/videos/comparisons/self-driven/aigc/sample3-xdub.mp4", poster: "" },
        { label: "LipForcing", src: "./assets/videos/comparisons/self-driven/aigc/sample3-lipforcing.mp4", poster: "" },
        { label: "KeySync", src: "./assets/videos/comparisons/self-driven/aigc/sample3-keysync.mp4", poster: "" },
        { label: "LatentSync", src: "./assets/videos/comparisons/self-driven/aigc/sample3-latentsync.mp4", poster: "" },
      ],
    },
    {
      id: "self-aigc-04",
      setting: "self",
      subgroup: "aigc-video",
      scenario: "AIGC Video · Sample 4",
      title: "AIGC-generated video reconstruction · Sample 4",
      description: "面向私人书房场景 AIGC 生产视频的同源音频重建案例。",
      tags: ["Same identity", "AIGC video", "Private study"],
      methods: [
        { label: "Input", src: "./assets/videos/comparisons/self-driven/aigc/sample4-input.mp4", poster: "" },
        { label: "TBDub", src: "./assets/videos/comparisons/self-driven/aigc/sample4-ours.mp4", poster: "", highlight: true },
        { label: "X-Dub", src: "./assets/videos/comparisons/self-driven/aigc/sample4-xdub.mp4", poster: "" },
        { label: "LipForcing", src: "./assets/videos/comparisons/self-driven/aigc/sample4-lipforcing.mp4", poster: "" },
        { label: "KeySync", src: "./assets/videos/comparisons/self-driven/aigc/sample4-keysync.mp4", poster: "" },
        { label: "LatentSync", src: "./assets/videos/comparisons/self-driven/aigc/sample4-latentsync.mp4", poster: "" },
      ],
    },
    {
      id: "self-aigc-05",
      setting: "self",
      subgroup: "aigc-video",
      scenario: "AIGC Video · Sample 5",
      title: "AIGC-generated video reconstruction · Sample 5",
      description: "面向艺术工作室场景 AIGC 生产视频的同源音频重建案例。",
      tags: ["Same identity", "AIGC video", "Art studio"],
      methods: [
        { label: "Input", src: "./assets/videos/comparisons/self-driven/aigc/sample5-input.mp4", poster: "" },
        { label: "TBDub", src: "./assets/videos/comparisons/self-driven/aigc/sample5-ours.mp4", poster: "", highlight: true },
        { label: "X-Dub", src: "./assets/videos/comparisons/self-driven/aigc/sample5-xdub.mp4", poster: "" },
        { label: "LipForcing", src: "./assets/videos/comparisons/self-driven/aigc/sample5-lipforcing.mp4", poster: "" },
        { label: "KeySync", src: "./assets/videos/comparisons/self-driven/aigc/sample5-keysync.mp4", poster: "" },
        { label: "LatentSync", src: "./assets/videos/comparisons/self-driven/aigc/sample5-latentsync.mp4", poster: "" },
      ],
    },
    {
      id: "cross-large-pose",
      setting: "cross",
      subgroup: "large-pose",
      scenario: "01 · Large Pose · Sample 1",
      title: "Large-pose robustness · Sample 1",
      description: "跨音频驱动下的大角度侧脸、转头和显著姿态变化案例。",
      tags: ["Cross audio", "Large pose"],
      methods: [
        { label: "Input", src: "./assets/videos/comparisons/large-pose/sample1-input.mp4", poster: "" },
        { label: "TBDub", src: "./assets/videos/comparisons/large-pose/sample1-ours.mp4", poster: "", highlight: true },
        { label: "TBDub (2-step)", src: "./assets/videos/comparisons/large-pose/sample1-ours-2step.mp4", poster: "", highlight: true },
        { label: "X-Dub", src: "./assets/videos/comparisons/large-pose/sample1-xdub.mp4", poster: "" },
        { label: "LipForcing", src: "./assets/videos/comparisons/large-pose/sample1-lipforcing.mp4", poster: "" },
        { label: "KeySync", src: "./assets/videos/comparisons/large-pose/sample1-keysync.mp4", poster: "" },
        { label: "LatentSync", src: "./assets/videos/comparisons/large-pose/sample1-latentsync.mp4", poster: "" },
      ],
    },
    {
      id: "cross-large-pose-02",
      setting: "cross",
      subgroup: "large-pose",
      scenario: "01 · Large Pose · Sample 2",
      title: "Large-pose robustness · Sample 2",
      description: "第二组跨音频驱动下的大角度侧脸、转头和显著姿态变化案例。",
      tags: ["Cross audio", "Large pose"],
      methods: [
        { label: "Input", src: "./assets/videos/comparisons/large-pose/sample2-input.mp4", poster: "" },
        { label: "TBDub", src: "./assets/videos/comparisons/large-pose/sample2-ours.mp4", poster: "", highlight: true },
        { label: "TBDub (2-step)", src: "./assets/videos/comparisons/large-pose/sample2-ours-2step.mp4", poster: "", highlight: true },
        { label: "X-Dub", src: "./assets/videos/comparisons/large-pose/sample2-xdub.mp4", poster: "" },
        { label: "LipForcing", src: "./assets/videos/comparisons/large-pose/sample2-lipforcing.mp4", poster: "" },
        { label: "KeySync", src: "./assets/videos/comparisons/large-pose/sample2-keysync.mp4", poster: "" },
        { label: "LatentSync", src: "./assets/videos/comparisons/large-pose/sample2-latentsync.mp4", poster: "" },
      ],
    },
    {
      id: "cross-occlusion-01",
      setting: "cross",
      subgroup: "occlusion",
      scenario: "02 · Occlusion · Sample 1",
      title: "Occlusion robustness · Sample 1",
      description: "真实场景遮挡下的跨音频口型重绘与四种方法对比。",
      tags: ["Cross audio", "Occlusion"],
      methods: [
        { label: "Input", src: "./assets/videos/comparisons/occlusion/sample1-input.mp4", poster: "" },
        { label: "TBDub", src: "./assets/videos/comparisons/occlusion/sample1-ours.mp4", poster: "", highlight: true },
        { label: "TBDub (2-step)", src: "./assets/videos/comparisons/occlusion/sample1-ours-2step.mp4", poster: "", highlight: true },
        { label: "X-Dub", src: "./assets/videos/comparisons/occlusion/sample1-xdub.mp4", poster: "" },
        { label: "LipForcing", src: "./assets/videos/comparisons/occlusion/sample1-lipforcing.mp4", poster: "" },
        { label: "KeySync", src: "./assets/videos/comparisons/occlusion/sample1-keysync.mp4", poster: "" },
        { label: "LatentSync", src: "./assets/videos/comparisons/occlusion/sample1-latentsync.mp4", poster: "" },
      ],
    },
    {
      id: "cross-occlusion-02",
      setting: "cross",
      subgroup: "occlusion",
      scenario: "02 · Occlusion · Sample 2",
      title: "Occlusion robustness · Sample 2",
      description: "另一组真实遮挡场景，用于观察嘴部边界、身份保持与时序稳定性。",
      tags: ["Cross audio", "Occlusion"],
      methods: [
        { label: "Input", src: "./assets/videos/comparisons/occlusion/sample2-input.mp4", poster: "" },
        { label: "TBDub", src: "./assets/videos/comparisons/occlusion/sample2-ours.mp4", poster: "", highlight: true },
        { label: "TBDub (2-step)", src: "./assets/videos/comparisons/occlusion/sample2-ours-2step.mp4", poster: "", highlight: true },
        { label: "X-Dub", src: "./assets/videos/comparisons/occlusion/sample2-xdub.mp4", poster: "" },
        { label: "LipForcing", src: "./assets/videos/comparisons/occlusion/sample2-lipforcing.mp4", poster: "" },
        { label: "KeySync", src: "./assets/videos/comparisons/occlusion/sample2-keysync.mp4", poster: "" },
        { label: "LatentSync", src: "./assets/videos/comparisons/occlusion/sample2-latentsync.mp4", poster: "" },
      ],
    },
    {
      id: "cross-occlusion-03",
      setting: "cross",
      subgroup: "occlusion",
      scenario: "02 · Occlusion · Sample 3",
      title: "Occlusion robustness · Sample 3",
      description: "第三组真实遮挡场景，用于比较不同方法的口型同步、身份保持与时序稳定性。",
      tags: ["Cross audio", "Occlusion"],
      methods: [
        { label: "Input", src: "./assets/videos/comparisons/occlusion/sample3-input.mp4", poster: "" },
        { label: "TBDub", src: "./assets/videos/comparisons/occlusion/sample3-ours.mp4", poster: "", highlight: true },
        { label: "TBDub (2-step)", src: "./assets/videos/comparisons/occlusion/sample3-ours-2step.mp4", poster: "", highlight: true },
        { label: "X-Dub", src: "./assets/videos/comparisons/occlusion/sample3-xdub.mp4", poster: "" },
        { label: "LipForcing", src: "./assets/videos/comparisons/occlusion/sample3-lipforcing.mp4", poster: "" },
        { label: "KeySync", src: "./assets/videos/comparisons/occlusion/sample3-keysync.mp4", poster: "" },
        { label: "LatentSync", src: "./assets/videos/comparisons/occlusion/sample3-latentsync.mp4", poster: "" },
      ],
    },
    {
      id: "cross-rapid-head-motion-01",
      setting: "cross",
      subgroup: "rapid-head-motion",
      scenario: "03 · Rapid Head Motion · Sample 1",
      title: "Rapid head-motion robustness · Sample 1",
      description: "跨音频驱动下的快速头部运动与高频抖动场景，用于检验困难动态条件下的口型稳定性、身份保持与时序一致性。",
      tags: ["Cross audio", "Rapid head motion", "Robustness"],
      methods: [
        { label: "Input", src: "./assets/videos/comparisons/rapid-head-motion/sample1-input.mp4", poster: "" },
        { label: "TBDub", src: "./assets/videos/comparisons/rapid-head-motion/sample1-ours.mp4", poster: "", highlight: true },
        { label: "TBDub (2-step)", src: "./assets/videos/comparisons/rapid-head-motion/sample1-ours-2step.mp4", poster: "", highlight: true },
        { label: "X-Dub", src: "./assets/videos/comparisons/rapid-head-motion/sample1-xdub.mp4", poster: "" },
        { label: "LipForcing", src: "./assets/videos/comparisons/rapid-head-motion/sample1-lipforcing.mp4", poster: "" },
        { label: "KeySync", src: "./assets/videos/comparisons/rapid-head-motion/sample1-keysync.mp4", poster: "" },
        { label: "LatentSync", src: "./assets/videos/comparisons/rapid-head-motion/sample1-latentsync.mp4", poster: "" },
      ],
    },
    {
      id: "cross-rapid-head-motion-02",
      setting: "cross",
      subgroup: "rapid-head-motion",
      scenario: "03 · Rapid Head Motion · Sample 2",
      title: "Rapid head-motion robustness · Sample 2",
      description: "第二组快速头部运动与高频抖动场景，用于进一步检验困难动态条件下的口型稳定性、身份保持与时序一致性。",
      tags: ["Cross audio", "Rapid head motion", "Robustness"],
      methods: [
        { label: "Input", src: "./assets/videos/comparisons/rapid-head-motion/sample2-input.mp4", poster: "" },
        { label: "TBDub", src: "./assets/videos/comparisons/rapid-head-motion/sample2-ours.mp4", poster: "", highlight: true },
        { label: "TBDub (2-step)", src: "./assets/videos/comparisons/rapid-head-motion/sample2-ours-2step.mp4", poster: "", highlight: true },
        { label: "X-Dub", src: "./assets/videos/comparisons/rapid-head-motion/sample2-xdub.mp4", poster: "" },
        { label: "LipForcing", src: "./assets/videos/comparisons/rapid-head-motion/sample2-lipforcing.mp4", poster: "" },
        { label: "KeySync", src: "./assets/videos/comparisons/rapid-head-motion/sample2-keysync.mp4", poster: "" },
        { label: "LatentSync", src: "./assets/videos/comparisons/rapid-head-motion/sample2-latentsync.mp4", poster: "" },
      ],
    },
    {
      id: "cross-in-the-wild-01",
      setting: "cross",
      subgroup: "in-the-wild",
      scenario: "04 · In-the-wild · Sample 1",
      title: "Diverse in-the-wild videos · Sample 1",
      description: "随机真实视频中的跨音频驱动结果，覆盖自然光照、构图与人物动态。",
      tags: ["Cross audio", "In-the-wild"],
      methods: [
        { label: "Input", src: "./assets/videos/comparisons/in-the-wild/sample1-input.mp4", poster: "" },
        { label: "TBDub", src: "./assets/videos/comparisons/in-the-wild/sample1-ours.mp4", poster: "", highlight: true },
        { label: "TBDub (2-step)", src: "./assets/videos/comparisons/in-the-wild/sample1-ours-2step.mp4", poster: "", highlight: true },
        { label: "X-Dub", src: "./assets/videos/comparisons/in-the-wild/sample1-xdub.mp4", poster: "" },
        { label: "LipForcing", src: "./assets/videos/comparisons/in-the-wild/sample1-lipforcing.mp4", poster: "" },
        { label: "KeySync", src: "./assets/videos/comparisons/in-the-wild/sample1-keysync.mp4", poster: "" },
        { label: "LatentSync", src: "./assets/videos/comparisons/in-the-wild/sample1-latentsync.mp4", poster: "" },
      ],
    },
    {
      id: "cross-in-the-wild-02",
      setting: "cross",
      subgroup: "in-the-wild",
      scenario: "04 · In-the-wild · Sample 2",
      title: "Diverse in-the-wild videos · Sample 2",
      description: "第二组随机真实视频，用于比较不同方法的口型同步、身份保持与时序稳定性。",
      tags: ["Cross audio", "In-the-wild"],
      methods: [
        { label: "Input", src: "./assets/videos/comparisons/in-the-wild/sample2-input.mp4", poster: "" },
        { label: "TBDub", src: "./assets/videos/comparisons/in-the-wild/sample2-ours.mp4", poster: "", highlight: true },
        { label: "TBDub (2-step)", src: "./assets/videos/comparisons/in-the-wild/sample2-ours-2step.mp4", poster: "", highlight: true },
        { label: "X-Dub", src: "./assets/videos/comparisons/in-the-wild/sample2-xdub.mp4", poster: "" },
        { label: "LipForcing", src: "./assets/videos/comparisons/in-the-wild/sample2-lipforcing.mp4", poster: "" },
        { label: "KeySync", src: "./assets/videos/comparisons/in-the-wild/sample2-keysync.mp4", poster: "" },
        { label: "LatentSync", src: "./assets/videos/comparisons/in-the-wild/sample2-latentsync.mp4", poster: "" },
      ],
    },
    {
      id: "cross-in-the-wild-03",
      setting: "cross",
      subgroup: "in-the-wild",
      scenario: "04 · In-the-wild · Sample 3",
      title: "Diverse in-the-wild videos · Sample 3",
      description: "第三组随机真实视频，进一步展示复杂真实场景中的生成质量与鲁棒性。",
      tags: ["Cross audio", "In-the-wild"],
      methods: [
        { label: "Input", src: "./assets/videos/comparisons/in-the-wild/sample3-input.mp4", poster: "" },
        { label: "TBDub", src: "./assets/videos/comparisons/in-the-wild/sample3-ours.mp4", poster: "", highlight: true },
        { label: "TBDub (2-step)", src: "./assets/videos/comparisons/in-the-wild/sample3-ours-2step.mp4", poster: "", highlight: true },
        { label: "X-Dub", src: "./assets/videos/comparisons/in-the-wild/sample3-xdub.mp4", poster: "" },
        { label: "LipForcing", src: "./assets/videos/comparisons/in-the-wild/sample3-lipforcing.mp4", poster: "" },
        { label: "KeySync", src: "./assets/videos/comparisons/in-the-wild/sample3-keysync.mp4", poster: "" },
        { label: "LatentSync", src: "./assets/videos/comparisons/in-the-wild/sample3-latentsync.mp4", poster: "" },
      ],
    },
    {
      id: "cross-in-the-wild-04",
      setting: "cross",
      subgroup: "in-the-wild",
      scenario: "04 · In-the-wild · Sample 4",
      title: "Diverse in-the-wild videos · Sample 4",
      description: "第四组随机真实视频，展示跨音频驱动在多样真实场景中的生成质量与鲁棒性。",
      tags: ["Cross audio", "In-the-wild"],
      methods: [
        { label: "Input", src: "./assets/videos/comparisons/in-the-wild/sample4-input.mp4", poster: "" },
        { label: "TBDub", src: "./assets/videos/comparisons/in-the-wild/sample4-ours.mp4", poster: "", highlight: true },
        { label: "TBDub (2-step)", src: "./assets/videos/comparisons/in-the-wild/sample4-ours-2step.mp4", poster: "", highlight: true },
        { label: "X-Dub", src: "./assets/videos/comparisons/in-the-wild/sample4-xdub.mp4", poster: "" },
        { label: "LipForcing", src: "./assets/videos/comparisons/in-the-wild/sample4-lipforcing.mp4", poster: "" },
        { label: "KeySync", src: "./assets/videos/comparisons/in-the-wild/sample4-keysync.mp4", poster: "" },
        { label: "LatentSync", src: "./assets/videos/comparisons/in-the-wild/sample4-latentsync.mp4", poster: "" },
      ],
    },
    {
      id: "cross-in-the-wild-05",
      setting: "cross",
      subgroup: "in-the-wild",
      scenario: "04 · In-the-wild · Sample 5",
      title: "Diverse in-the-wild videos · Sample 5",
      description: "第五组随机真实视频，进一步展示跨音频驱动在复杂真实场景中的生成质量与鲁棒性。",
      tags: ["Cross audio", "In-the-wild"],
      methods: [
        { label: "Input", src: "./assets/videos/comparisons/in-the-wild/sample5-input.mp4", poster: "" },
        { label: "TBDub", src: "./assets/videos/comparisons/in-the-wild/sample5-ours.mp4", poster: "", highlight: true },
        { label: "TBDub (2-step)", src: "./assets/videos/comparisons/in-the-wild/sample5-ours-2step.mp4", poster: "", highlight: true },
        { label: "X-Dub", src: "./assets/videos/comparisons/in-the-wild/sample5-xdub.mp4", poster: "" },
        { label: "LipForcing", src: "./assets/videos/comparisons/in-the-wild/sample5-lipforcing.mp4", poster: "" },
        { label: "KeySync", src: "./assets/videos/comparisons/in-the-wild/sample5-keysync.mp4", poster: "" },
        { label: "LatentSync", src: "./assets/videos/comparisons/in-the-wild/sample5-latentsync.mp4", poster: "" },
      ],
    },
  ],

  method: {
    title: "Method",
    intro: "TBDub 以 X-Dub/Wan 的无显式口部遮罩、参考条件视频编辑框架为基础。完整源视频与 motion context 约束身份和时空结构，帧对齐语音控制目标发音；生产域后训练得到 30 步 Teacher，任务感知 DMD2 进一步将其压缩为 2 步 Student。",
    pipelineAlt: "TBDub 整体流程：源视频经 VAE 编码为参考与目标 latent，motion context 注入目标序列；DiT 联合建模参考 token、噪声目标 token 与多层 HuBERT 驱动音频，随后由 VAE 解码得到配音视频。",
    facts: [
      { value: "X-Dub/Wan", label: "继承的 mask-free 主干" },
      { value: "78,161", label: "当前记录的过滤后伪配对" },
      { value: "30 → 2", label: "Teacher / student steps" },
      { value: "42.49×", label: "DiT 阶段加速（H20）" },
    ],
    pipeline: [
      {
        index: "01",
        title: "Source video",
        meta: "TRACK · CROP · 3D VAE",
        text: "将完整参考视频编码为空间—时间 latent；继承的 motion context 固定部分目标 latent，为身份、姿态与局部运动提供约束。",
        tone: "visual",
      },
      {
        index: "02",
        title: "Driving audio",
        meta: "HUBERT LARGE · L9–12",
        text: "融合 HuBERT 多层语音表征，并为每个视频 latent 帧构造局部音频窗口。",
        tone: "audio",
      },
      {
        index: "03",
        title: "Joint DiT editor",
        meta: "REF + NOISY TARGET TOKENS",
        text: "继承 X-Dub 的参考—目标联合 token 建模、分离 timestep 与 3D RoPE；自注意力融合时空上下文，音频与文本交叉注意力作用于目标分支。",
        tone: "featured",
      },
      {
        index: "04",
        title: "Flow prediction",
        meta: "CONDITIONAL VELOCITY FIELD",
        text: "Flow Matching 从噪声 target latent 预测条件速度场，并逐步恢复编辑后的目标 latent。",
        tone: "flow",
      },
      {
        index: "05",
        title: "Video output",
        meta: "VAE DECODE · COMPOSITE",
        text: "仅保留目标 token，解码编辑后的人脸序列并贴回原视频，保留非目标画面区域。",
        tone: "output",
      },
    ],
    details: [
      {
        index: "A",
        eyebrow: "TASK-RELEVANT PSEUDO PAIRS",
        title: "Break the reference-copy shortcut",
        text: "直接自重建容易让模型复制参考口型并弱化音频条件。我们以重配音视频作为条件参考、干净原视频作为目标，并使用原始对齐音频监督；参考与目标保持同一身份和场景但具有不同口型，使音频成为恢复正确发音动态的必要条件。",
        meta: ["89,462 candidates", "78,161 retained", "87.37% retention", "Audiovisual calibration"],
      },
      {
        index: "B",
        eyebrow: "PRODUCTION DATA & CONDITIONING",
        title: "Adapt to production data and recover oral detail",
        text: "后训练以 3:1 混合直播与绿幕棚拍数据。光照与口部退化仅作用于条件参考，干净目标保持不变；同身份清晰口部先验补充唇齿纹理，多层 HuBERT 特征提供帧对齐的语音条件。",
        meta: ["Livestream : studio = 3 : 1", "Conditioning-only augmentation", "Clean oral prior", "HuBERT-large L9–12"],
      },
      {
        index: "C",
        eyebrow: "WEIGHTED FLOW MATCHING",
        title: "Focus Teacher learning on faces and temporal stability",
        text: "30 步 Teacher 保持 Flow Matching 目标，并提高人脸、口部、后续帧以及无 motion context 时冷启动首帧的训练权重，使监督更集中于唇齿细节与长时序稳定性。",
        meta: ["Face / mouth weighting", "Later-frame weighting", "Cold-start first latent", "Motion dropout"],
      },
      {
        index: "D",
        eyebrow: "TASK-AWARE TWO-STEP DISTILLATION",
        title: "Compress guided generation into two single-route steps",
        text: "以 X-Dub 的无条件、仅参考和参考加音频三路动态 CFG 构造 guided Teacher score，并在一致条件下训练 Student 与 FakeScore。Student 保留完整两步可微轨迹，每步仅执行一次全条件 DiT 前向；区域选择性 warmup 与 FP32 EMA 用于稳定少步训练。",
        formula: "30 steps × 3 guidance routes  →  2 steps × 1 conditional route",
        meta: ["Conditional DMD2", "2,000-step selective warmup", "FP32 EMA · β = 0.97", "5 FakeScore : 1 Student"],
      },
    ],
  },

  quantitativeResults: {
    limitation: {
      label: "EVALUATION SCOPE & LIMITATION",
      title: "Full-reference metrics describe matched reconstruction, not the complete dubbing task",
      text: "PSNR、SSIM、LPIPS、FID 与 CSIM 依赖逐帧真值，主要在使用原视频音频的 self-driven setting 中衡量对齐重建、感知质量、分布真实感和身份保持。Cross-driven setting 不存在唯一的逐帧口型真值，因此使用 SyncNet 指标、Response Mouth PSNR、主观 MOS 与视频对比作补充。客观指标与人工观感并不完全一致，尤其不能由单个重建或同步指标替代对跨音频口型准确性、自然度和困难场景鲁棒性的直接观察。",
    },
    summary: [
      { name: "VISUAL QUALITY", value: "PSNR · SSIM · LPIPS · FID", note: "Paired fidelity, perceptual quality, and distribution realism · TalkVid" },
      { name: "NO-REFERENCE SYNC", value: "LSE-C ↑ · LSE-D ↓", note: "Available for both self-driven and cross-audio results" },
      { name: "SUBJECTIVE STUDY", value: "114 Ratings / Method", note: "38 TalkVid clips · 3 independent raters" },
    ],
    readingNotes: [
      {
        eyebrow: "01 · PAIRED QUALITY",
        title: "PSNR / SSIM / LPIPS",
        text: "只在自驱动 TalkVid 组计算，因为原片提供逐帧对齐真值。PSNR / SSIM 越高越好，LPIPS 越低越好；LPIPS 使用感知特征比较画面差异，face 与 mouth 两个区域有助于区分整体人脸保真度和唇部局部退化。",
      },
      {
        eyebrow: "02 · NO-REFERENCE SYNC",
        title: "LSE-C / LSE-D",
        text: "SyncNet 在时间偏移范围内寻找最佳音画对齐点。LSE-C 衡量最佳点是否突出，越高越好；LSE-D 衡量最佳点的嵌入距离，越低越好。两者应成对阅读。",
      },
      {
        eyebrow: "03 · DISTRIBUTION QUALITY",
        title: "FID",
        text: "比较真实帧与生成帧在特征空间中的整体分布距离，越低越好。FID 反映画面分布级真实感，不衡量身份保持或口型同步；当前仅有 38 个样本，数值应作为辅助参考。",
      },
      {
        eyebrow: "04 · IDENTITY PRESERVATION",
        title: "ArcFace CSIM",
        text: "使用 ArcFace（antelopev2 / glintr100）提取经过 5 点对齐的人脸 embedding，并计算生成帧与真值同帧的余弦相似度，越高越好。CSIM 衡量身份保持，但几乎不改动画面的方法天然更接近 1，因此需要与 resp_mouth_psnr 联合解读，不能单独排序。",
      },
    ],
    primaryColumns: [
      { key: "method", label: "Method", group: "" },
      { key: "psnrMouth", label: "PSNR ↑", group: "Mouth quality" },
      { key: "ssimMouth", label: "SSIM ↑", group: "Mouth quality" },
      { key: "lpipsFace", label: "LPIPS ↓", group: "Face quality" },
      { key: "lpipsMouth", label: "LPIPS ↓", group: "Mouth quality" },
      { key: "fid", label: "FID ↓", group: "Distribution quality" },
      { key: "csim", label: "CSIM ↑", group: "Identity" },
      { key: "lseC", label: "LSE-C ↑", group: "SyncNet" },
      { key: "lseD", label: "LSE-D ↓", group: "SyncNet" },
      { key: "respMouthPsnr", label: "PSNR ↔", group: "Response mouth" },
    ],
    columns: [
      { key: "method", label: "Method", group: "" },
      { key: "nRecon", label: "n_recon", group: "Samples" },
      { key: "nSync", label: "n_sync", group: "Samples" },
      { key: "psnrFull", label: "PSNR", group: "Full ↑" },
      { key: "ssimFull", label: "SSIM", group: "Full ↑" },
      { key: "psnrFace", label: "PSNR", group: "Face ↑" },
      { key: "ssimFace", label: "SSIM", group: "Face ↑" },
      { key: "psnrMouth", label: "PSNR", group: "Mouth ↑" },
      { key: "ssimMouth", label: "SSIM", group: "Mouth ↑" },
      { key: "lpipsFace", label: "LPIPS ↓", group: "Face quality" },
      { key: "lpipsMouth", label: "LPIPS ↓", group: "Mouth quality" },
      { key: "fid", label: "FID ↓", group: "Distribution quality" },
      { key: "csim", label: "CSIM ↑", group: "Identity" },
      { key: "lseC", label: "LSE-C ↑", group: "Sync" },
      { key: "lseD", label: "LSE-D ↓", group: "Sync" },
      { key: "respMouthPsnr", label: "PSNR ↔", group: "Response mouth" },
    ],
    rows: [
      { method: "Ground truth", nRecon: "0", nSync: "38", psnrFull: "—", ssimFull: "—", psnrFace: "—", ssimFace: "—", psnrMouth: "—", ssimMouth: "—", lpipsFace: "—", lpipsMouth: "—", fid: "—", csim: "—", lseC: "6.28", lseD: "8.35", respMouthPsnr: "—", reference: true },
      { method: "X-Dub", nRecon: "38", nSync: "38", psnrFull: "—", ssimFull: "—", psnrFace: "—", ssimFace: "—", psnrMouth: "22.20", ssimMouth: "0.76", lpipsFace: "0.07", lpipsMouth: "0.08", fid: "9.96", csim: "0.88", lseC: "5.66", lseD: "9.28", respMouthPsnr: "23.05" },
      { method: "LipForcing", nRecon: "38", nSync: "38", psnrFull: "—", ssimFull: "—", psnrFace: "—", ssimFace: "—", psnrMouth: "24.33", ssimMouth: "0.82", lpipsFace: "0.05", lpipsMouth: "0.06", fid: "4.34", csim: "0.91", lseC: "6.13", lseD: "8.37", respMouthPsnr: "29.28" },
      { method: "KeySync", nRecon: "38", nSync: "38", psnrFull: "—", ssimFull: "—", psnrFace: "—", ssimFace: "—", psnrMouth: "23.23", ssimMouth: "0.82", lpipsFace: "0.05", lpipsMouth: "0.08", fid: "16.19", csim: "0.86", lseC: "6.97", lseD: "7.82", respMouthPsnr: "22.61" },
      { method: "LatentSync", nRecon: "38", nSync: "38", psnrFull: "—", ssimFull: "—", psnrFace: "—", ssimFace: "—", psnrMouth: "31.30", ssimMouth: "0.95", lpipsFace: "0.01", lpipsMouth: "0.02", fid: "3.70", csim: "0.97", lseC: "7.76", lseD: "7.00", respMouthPsnr: "30.98" },
      { method: "TBDub Teacher", detail: "30 steps", nRecon: "38", nSync: "38", psnrFull: "—", ssimFull: "—", psnrFace: "—", ssimFace: "—", psnrMouth: "27.13", ssimMouth: "0.87", lpipsFace: "0.06", lpipsMouth: "0.06", fid: "9.40", csim: "0.91", lseC: "6.80", lseD: "7.98", respMouthPsnr: "25.67", highlight: true },
      { method: "TBDub Student", detail: "2 steps · EMA", nRecon: "38", nSync: "38", psnrFull: "—", ssimFull: "—", psnrFace: "—", ssimFace: "—", psnrMouth: "26.34", ssimMouth: "0.87", lpipsFace: "0.06", lpipsMouth: "0.06", fid: "9.10", csim: "0.91", lseC: "7.16", lseD: "7.89", respMouthPsnr: "23.64", highlight: true },
    ],
    protocol: [
      {
        name: "PSNR",
        text: "10·log10(255² / MSE)，单位 dB；约每增加 6 dB，像素均方根误差减半。容易偏爱小编辑区域和模糊结果。",
      },
      {
        name: "SSIM",
        text: "在亮度通道的局部窗口内比较亮度、对比度与结构关系，范围 0–1；比 PSNR 更关注局部纹理，但仍需要逐帧真值。",
      },
      {
        name: "LPIPS",
        text: "使用预训练网络的深层特征比较生成结果与逐帧真值的感知距离，越低越好；分别在人脸与口部区域统计，38 条样本均成功计算。",
      },
      {
        name: "Regions",
        text: "face 使用全片中位人脸框；mouth 取人脸框横向 25%–75%、纵向 55%–95%。full 容易被未编辑背景支配。",
      },
      {
        name: "SyncNet",
        text: "嘴部缩放至 224×224，以 5 帧为一组，与 MFCC 音频嵌入在 ±15 帧内搜索最佳偏移；LSE-C 与 LSE-D 共同描述对齐。",
      },
      {
        name: "FID",
        text: "比较真实帧与生成帧的 Inception 特征分布，数值越低表示整体视觉分布越接近真实数据；不评价逐帧重建、身份保持或音画同步。",
      },
      {
        name: "ArcFace CSIM",
        text: "使用 antelopev2 / glintr100 对 5 点对齐后的人脸提取 embedding，计算生成帧与真值同帧的余弦相似度；越高表示身份特征越接近。",
      },
    ],
  },

  subjectiveResults: {
    intro: "三名评测者在同一组 38 条 TalkVid 视频上对六种匿名、逐案例随机排序的方法输出进行 0–5 分 MOS 评分。每种方法包含 114 条评分记录；Ground Truth 仅用于辅助判断身份与整体外观，不参与评分。",
    columns: [
      { key: "method", label: "Method", group: "" },
      { key: "ratings", label: "Ratings", group: "Records" },
      { key: "lipSync", label: "MOS ↑", group: "Lip sync" },
      { key: "identity", label: "MOS ↑", group: "Identity" },
      { key: "visual", label: "MOS ↑", group: "Visual quality" },
    ],
    rows: [
      { method: "KeySync", ratings: "114", lipSync: "2.75", identity: "2.40", visual: "2.33" },
      { method: "LatentSync", ratings: "114", lipSync: "1.91", identity: "2.23", visual: "1.87" },
      { method: "LipForcing", ratings: "114", lipSync: "2.18", identity: "2.88", visual: "2.52" },
      { method: "X-Dub", ratings: "114", lipSync: "3.57", identity: "2.83", visual: "2.88" },
      { method: "TBDub Teacher", detail: "30 steps", ratings: "114", lipSync: "3.71", identity: "3.78", visual: "3.78", highlight: true },
      { method: "TBDub Student", detail: "2 steps · EMA", ratings: "114", lipSync: "3.85", identity: "3.72", visual: "3.80", highlight: true },
    ],
    note: "当前仅报告 MOS 均值，尚未进行统计显著性检验，因此不将 0.02 等微小差异解释为显著提升。",
    analysisTitle: "主观评分显示质量提升在两步蒸馏后得到较好保留",
    analysis: "相较 X-Dub，TBDub Teacher 的 Lip-sync、Identity 与 Visual-quality MOS 分别提高 0.14、0.95 和 0.90，主要优势体现在身份一致性和整体画质。两步 Student 的三项得分为 3.85、3.72 和 3.80：其 Lip-sync 与 Visual-quality 均值最高，Identity 仅比 Teacher 低 0.06，说明在大幅减少采样步数后，主观生成质量仍得到较好保留。",
  },

  efficiency: {
    summary: [
      { name: "STUDENT THROUGHPUT", value: "7.13 FPS", note: "Effective FPS · 376 valid frames" },
      { name: "CORE PIPELINE SPEEDUP", value: "13.93×", note: "734.75 s → 52.76 s" },
      { name: "DIT SPEEDUP", value: "42.49×", note: "696.77 s → 16.40 s" },
    ],
    throughputColumns: [
      { key: "method", label: "Method", group: "" },
      { key: "config", label: "Model / steps", group: "Configuration" },
      { key: "fps", label: "FPS ↑", group: "Throughput" },
    ],
    throughputRows: [
      { method: "KeySync", config: "Default best configuration", fps: "1.05" },
      { method: "LatentSync", config: "Default best configuration", fps: "1.31" },
      { method: "LipForcing", config: "14B · full Wan VAE", fps: "2.83" },
      { method: "Original X-Dub", config: "30 steps", fps: "0.51" },
      { method: "TBDub Teacher", config: "30 steps", fps: "0.51", highlight: true },
      { method: "TBDub Student", config: "2 steps · EMA", fps: "7.13", highlight: true },
    ],
    profileColumns: [
      { key: "method", label: "Method", group: "" },
      { key: "encode", label: "VAE enc. ↓", group: "Latency (s)" },
      { key: "dit", label: "DiT ↓", group: "Latency (s)" },
      { key: "other", label: "Other ↓", group: "Latency (s)" },
      { key: "decode", label: "VAE dec. ↓", group: "Latency (s)" },
      { key: "total", label: "Total ↓", group: "Latency (s)" },
      { key: "fps", label: "FPS ↑", group: "Effective" },
    ],
    profileRows: [
      { method: "Teacher", detail: "30 steps", encode: "9.29", dit: "696.77", other: "5.15", decode: "23.54", total: "734.75", fps: "0.51", highlight: true },
      { method: "Student", detail: "2 steps", encode: "9.27", dit: "16.40", other: "3.55", decode: "23.54", total: "52.76", fps: "7.13", highlight: true },
    ],
    scope: "测试使用单张 NVIDIA H20、512×512 输入。计时边界从第一次 VAE 编码开始，到最终 VAE 解码结束；不包含模型加载、HuBERT 音频编码、人脸检测与裁剪、颜色校正、贴回、视频编码和文件写入，因此这里报告的是 VAE-to-VAE 核心生成吞吐，而非完整应用端到端速度。",
  },

  citation: `@article{tbdub2026,
  title   = {TBDub: Production-Oriented Visual Dubbing},
  author  = {Bihan Li and Xinyang Li and Zeran Xu and Meiguang Jin and Junfeng Ma},
  journal = {arXiv preprint},
  year    = {2026}
}`,
};

// Public OSS sources keep the GitHub Pages bundle lightweight. The same URLs
// use HTTPS so browsers do not block media on the HTTPS project page.
(() => {
  const base = "https://live-aigc-dh-cloud.oss-cn-zhangjiakou.aliyuncs.com/qifu/tmp/oss_cp/";
  const url = (filename) => `${base}${filename}`;
  const standard = ({ stem, input, ours, baseline, student, xdub = baseline, lipforcing = baseline, keysync = baseline, latentsync = baseline }) => ({
    Input: url(`input_videovideo${stem}_${input}.mp4`),
    TBDub: url(`ours_pasted_videovideo${stem}_idx0_pasted_${ours}.mp4`),
    ...(student ? { "TBDub (2-step)": url(student) } : {}),
    "X-Dub": url(`xdub_videovideo${stem}_pasted_${xdub}.mp4`),
    LipForcing: url(`lipforcing_videovideo${stem}_${lipforcing}.mp4`),
    KeySync: url(`keysync_videovideo${stem}_${keysync}.mp4`),
    LatentSync: url(`latentsync_videovideo${stem}_out_${latentsync}.mp4`),
  });

  const sources = {
    "self-01": standard({ stem: "RNl80o2ZmAk-scene42_scene1", input: "20260824_014237", ours: "20260824_104316", baseline: "20260824_011435", student: "videovideoRNl80o2ZmAk-scene42_scene1_idx0_pasted_20260904_013544.mp4" }),
    "self-english-01": standard({ stem: "K5P_ckvrH84-scene181_scene1", input: "20260824_014237", ours: "20260824_104316", baseline: "20260824_011434", student: "videovideoK5P_ckvrH84-scene181_scene1_idx0_pasted_20260904_013541.mp4" }),
    "self-korean-01": standard({ stem: "eP1Ekcs9QqQ-scene2_scene145", input: "20260824_014238", ours: "20260824_104318", baseline: "20260824_011438", student: "videovideoeP1Ekcs9QqQ-scene2_scene145_idx0_pasted_20260904_013539.mp4" }),
    "self-russian-01": standard({ stem: "QpxeCzBBJZQ-scene37_scene8", input: "20260824_014237", ours: "20260824_104316", baseline: "20260824_011435", student: "videovideoQpxeCzBBJZQ-scene37_scene8_idx0_pasted_20260904_013543.mp4" }),
    "self-japanese-01": standard({ stem: "yyss0igkVx4-scene67_scene6", input: "20260824_014238", ours: "20260824_104319", baseline: "20260824_011441", student: "videovideoyyss0igkVx4-scene67_scene6_idx0_pasted_20260904_013547.mp4" }),

    "self-aigc-01": {
      Input: url("portrait-01-city-outdoor_20260819_140107.mp4"),
      TBDub: url("vid00_portrait-01-city-outdoor_20260819_140107_idx0_pasted_20260820_140500.mp4"),
      "X-Dub": url("vid00_portrait-01-city-outdoor_20260819_140107_pasted_20260824_164239.mp4"),
      LipForcing: url("vid00_20260824_162201.mp4"),
      KeySync: url("vid00_portrait-01-city-outdoor_20260819_140107_20260820_150956.mp4"),
      LatentSync: url("vid00_out_20260820_155123.mp4"),
    },
    "self-aigc-02": {
      Input: url("portrait-02-livestream-room_20260819_141603.mp4"),
      TBDub: url("vid01_portrait-02-livestream-room_20260819_141603_idx0_pasted_20260820_140500.mp4"),
      "X-Dub": url("vid01_portrait-02-livestream-room_20260819_141603_pasted_20260824_164239.mp4"),
      LipForcing: url("vid01_20260824_162201.mp4"),
      KeySync: url("vid01_portrait-02-livestream-room_20260819_141603_20260820_150956.mp4"),
      LatentSync: url("vid01_out_20260820_155123.mp4"),
    },
    "self-aigc-03": {
      Input: url("portrait-03-office_20260819_155140.mp4"),
      TBDub: url("vid02_portrait-03-office_20260819_155140_idx0_pasted_20260820_140501.mp4"),
      "X-Dub": url("vid02_portrait-03-office_20260819_155140_pasted_20260824_164240.mp4"),
      LipForcing: url("vid02_20260824_162201.mp4"),
      KeySync: url("vid02_portrait-03-office_20260819_155140_20260820_150957.mp4"),
      LatentSync: url("vid02_out_20260820_155123.mp4"),
    },
    "self-aigc-04": {
      Input: url("portrait-05-private-study_20260819_155217.mp4"),
      TBDub: url("vid04_portrait-05-private-study_20260819_155217_idx0_pasted_20260820_140502.mp4"),
      "X-Dub": url("vid04_portrait-05-private-study_20260819_155217_pasted_20260824_164240.mp4"),
      LipForcing: url("vid04_20260824_162201.mp4"),
      KeySync: url("vid04_portrait-05-private-study_20260819_155217_20260820_150957.mp4"),
      LatentSync: url("vid04_out_20260820_155123.mp4"),
    },
    "self-aigc-05": {
      Input: url("portrait-07-art-studio_20260819_155227.mp4"),
      TBDub: url("vid05_portrait-07-art-studio_20260819_155227_idx0_pasted_20260820_140502.mp4"),
      "X-Dub": url("vid05_portrait-07-art-studio_20260819_155227_pasted_20260824_164240.mp4"),
      LipForcing: url("vid05_20260824_162202.mp4"),
      KeySync: url("vid05_portrait-07-art-studio_20260819_155227_20260820_150957.mp4"),
      LatentSync: url("vid05_out_20260820_155124.mp4"),
    },

    "cross-large-pose": standard({ stem: "lddWWhzVMkI-scene46_scene5", input: "20260824_014238", ours: "20260824_000808", baseline: "20260823_224932", student: "videovideolddWWhzVMkI-scene46_scene5_idx0_pasted_20260904_013526.mp4" }),
    "cross-large-pose-02": standard({ stem: "Rl5Y9Eem3tc-scene47_scene6", input: "20260824_014237", ours: "20260824_000805", baseline: "20260823_224927", student: "videovideoRl5Y9Eem3tc-scene47_scene6_idx0_pasted_20260904_013530.mp4" }),
    "cross-occlusion-01": standard({ stem: "8UHw32CiOCU-scene83_scene4", input: "20260824_014237", ours: "20260824_000803", baseline: "20260823_224924", student: "videovideo8UHw32CiOCU-scene83_scene4_idx0_pasted_20260904_013517.mp4" }),
    "cross-occlusion-02": standard({ stem: "_Mi9viYt2g3s-scene21_scene2", input: "20260824_014238", ours: "20260824_000806", baseline: "20260823_224930", student: "videovideo_Mi9viYt2g3s-scene21_scene2_idx0_pasted_20260904_013526.mp4" }),
    "cross-occlusion-03": standard({ stem: "r7JQRKps8Jk-scene105_scene1", input: "20260824_014238", ours: "20260824_000808", baseline: "20260823_224933", xdub: "20260823_224932", student: "videovideor7JQRKps8Jk-scene105_scene1_idx0_pasted_20260904_013529.mp4" }),
    "cross-rapid-head-motion-01": standard({ stem: "_3a5nVhL-eb4-scene15_scene1", input: "20260824_014237", ours: "20260824_000806", baseline: "20260823_224929", student: "videovideo_3a5nVhL-eb4-scene15_scene1_idx0_pasted_20260904_013515.mp4" }),
    "cross-rapid-head-motion-02": standard({ stem: "J1mbRpQor-E-scene217_scene6", input: "20260824_014237", ours: "20260824_000804", baseline: "20260823_224925", student: "videovideoJ1mbRpQor-E-scene217_scene6_idx0_pasted_20260904_013522.mp4" }),
    "cross-in-the-wild-01": standard({ stem: "Ss1fcASwYT8-scene27_scene11", input: "20260824_014237", ours: "20260824_000806", baseline: "20260823_224928", student: "videovideoSs1fcASwYT8-scene27_scene11_idx0_pasted_20260904_013531.mp4" }),
    "cross-in-the-wild-02": standard({ stem: "_DWiGs8QEoXM-scene4_scene7", input: "20260824_014237", ours: "20260824_000806", baseline: "20260823_224929", student: "videovideo_DWiGs8QEoXM-scene4_scene7_idx0_pasted_20260904_013519.mp4" }),
    "cross-in-the-wild-03": standard({ stem: "_jXncD5ONQdg-scene5_scene5", input: "20260824_014238", ours: "20260824_000807", baseline: "20260823_224930", student: "videovideo_jXncD5ONQdg-scene5_scene5_idx0_pasted_20260904_013523.mp4" }),
    "cross-in-the-wild-04": standard({ stem: "_vBSB6HoJSeg-scene19_scene5", input: "20260824_014238", ours: "20260824_000807", baseline: "20260823_224930", student: "videovideo_vBSB6HoJSeg-scene19_scene5_idx0_pasted_20260904_013533.mp4" }),
    "cross-in-the-wild-05": standard({ stem: "igDXJuTVdyI-scene6_scene58", input: "20260824_014238", ours: "20260824_000808", baseline: "20260823_224931", student: "videovideoigDXJuTVdyI-scene6_scene58_idx0_pasted_20260904_013522.mp4" }),
  };

  for (const sample of window.PROJECT_DATA.qualitativeResults) {
    const sampleSources = sources[sample.id];
    if (!sampleSources) throw new Error(`Missing public video sources for ${sample.id}`);
    for (const method of sample.methods) {
      const source = sampleSources[method.label];
      if (!source) throw new Error(`Missing public video source for ${sample.id} / ${method.label}`);
      method.src = source;
    }
  }
})();
