// V1.1 is an inference/deployment iteration of the original Teacher and Student.
// VRAM data: the paired 2026-09-12 RTX PRO 5000 runs, not the paper's H20 table.
window.RELEASE_COPY = {
  en: {
    banner: "Less GPU memory. Simpler setup. Smaller downloads.",
    view: "What's new",
    eyebrow: "PROJECT UPDATES · SEPTEMBER 2026",
    title: "V1.1 · Easier to run",
    intro: "An inference and deployment update to V1.0: the same trained Teacher and Student, with one installation, compact checkpoints, and an optional mode for lower GPU memory usage.",
    cards: [
      {
        label: "SIMPLER SETUP",
        title: "One requirements.txt",
        text: "Install the validated MediaPipe 0.10.21 setup from one requirements.txt. It handles face detection, cropping, and landmark extraction. Inference uses a fixed prompt embedding, so no text encoder is loaded.",
        href: "https://github.com/TaoLiveAIGC/TBDub#requirements",
        link: "Installation guide",
      },
      {
        label: "SMALLER DOWNLOADS",
        title: "One 12.59 GB DiT per variant",
        text: "Choose Teacher or Student: each is a complete BF16 checkpoint of 12.59 GB, about 15.27 GB including the shared auxiliary models. V1.0's documented DiT downloads alone were 37.77 GB for Student and 22.87 GB for Teacher.",
        href: "https://github.com/TaoLiveAIGC/TBDub#checkpoints",
        link: "Choose your model",
      },
      {
        label: "LOWER GPU MEMORY",
        title: "Optional CPU offload",
        text: "Models stay on the GPU by default for speed. If memory runs out, rerun with --cpu-offload: measured process peaks were 15.01 GiB for Student and 19.49 GiB for Teacher, with more host RAM and transfer time.",
        href: "#gpu-memory",
        link: "Measurements and settings",
      },
    ],
    current: "One requirements.txt · MediaPipe · standalone BF16 models · optional CPU offload",
    previous: "Initial open-source release: inference code, Teacher, Student, and the original research results.",
    changelog: "Full V1.0 → V1.1 changelog",
    memory: {
      eyebrow: "V1.1 · GPU MEMORY",
      title: "Lower memory, with CPU offload",
      intro: "Models stay GPU-resident by default to prioritize speed. If inference runs out of GPU memory, manually rerun with --cpu-offload: inactive DiT/VAE weights stay in system RAM, and HuBERT enters the GPU only for audio feature extraction. The program does not detect GPU capacity, switch modes automatically, or retry an out-of-memory failure.",
      caption: "V1.1 process GPU memory peaks · RTX PRO 5000 72GB",
      columns: ["Model", "Default GPU-resident", "With --cpu-offload"],
      scope: "512 × 512 · 15.04-second audio · 376 output frames. Sampled per-process nvidia-smi memory, including CUDA overhead. Both columns use the optimized V1.1 models; this is a comparison of memory modes, separate from the paper's H20 speed benchmark.",
      cfgTitle: "Why does Teacher use more GPU memory?",
      cfg: "Teacher and Student have the same parameter count and BF16 weight size. Teacher evaluates three CFG branches together, sharing one set of weights but requiring more intermediate activations and workspaces; Student evaluates one branch. In this test, the full-sequence VAE decode dominated both resident-mode peaks. CPU offload made DiT denoising the peak stage, where Teacher's CFG requires more memory. Sampling steps mainly affect time, not memory in proportion to the step count.",
      detailsTitle: "Test settings, host RAM, and timing",
      settings: "Teacher: 30 steps, reference/audio CFG 2.5/10, sigma shift 5. Student: two steps, sigma shift 1, latent motion, default first-clip padding. CPU-offload runs completed with a 22 GiB PyTorch allocator limit. This is not a physical RTX 4090 test or a guarantee that arbitrarily long inputs fit in 24 GiB; longer sequences can still increase memory usage.",
      tradeoff: "Host-process RSS peaked at 21.9 GiB for Teacher and 21.3 GiB for Student, with additional RAM needed by the system. In single cold runs, inference plus output time changed from 563.6 to 595.3 seconds for Teacher and 63.1 to 82.1 seconds for Student. These timings exclude preprocessing, model loading, and process startup.",
      validation: "All 376 decoded video frames and the audio matched the respective resident-mode outputs exactly. Computation precision and sampling settings were preserved. Whole-GPU sampled peaks were 19.83 GiB for Teacher and 15.02 GiB for Student; allocator reserved memory is not added to allocated memory.",
      usage: "Usage and memory guidance",
    },
  },
  zh: {
    banner: "更低显存，更简单的安装，更小的模型下载。",
    view: "查看更新",
    eyebrow: "项目更新 · 2026 年 9 月",
    title: "V1.1 · 更容易运行",
    intro: "在 V1.0 基础上更新推理与部署流程：沿用已有 Teacher 和 Student，统一安装依赖、精简权重文件，并提供可选低显存模式。",
    cards: [
      {
        label: "更简单的安装",
        title: "统一一个 requirements.txt",
        text: "通过一个 requirements.txt 安装已验证的 MediaPipe 0.10.21 环境，完成人脸检测、裁剪和关键点提取。推理直接使用固定提示词嵌入，无需加载文本编码器。",
        href: "https://github.com/TaoLiveAIGC/TBDub#requirements",
        link: "查看安装指南",
      },
      {
        label: "更小的下载量",
        title: "每种 DiT 只需一个 12.59 GB 文件",
        text: "按需选择 Teacher 或 Student，每种都是完整的 BF16 权重，约 12.59 GB，连同共享辅助模型共约 15.27 GB。V1.0 指南中仅 DiT 的下载量就是 Student 37.77 GB、Teacher 22.87 GB。",
        href: "https://github.com/TaoLiveAIGC/TBDub#checkpoints",
        link: "选择需要的模型",
      },
      {
        label: "更低的显存占用",
        title: "可选 CPU 卸载",
        text: "默认让模型常驻 GPU，优先保证速度。遇到显存不足时，可手动添加 --cpu-offload 重跑。本次该模式的进程显存峰值为 Student 15.01 GiB、Teacher 19.49 GiB，代价是增加主机内存和传输耗时。",
        href: "#gpu-memory",
        link: "查看数据和测试条件",
      },
    ],
    current: "统一 requirements.txt · MediaPipe · 独立 BF16 权重 · 可选 CPU 卸载",
    previous: "首次开源：推理代码、Teacher、Student，以及原始研究结果。",
    changelog: "完整 V1.0 → V1.1 更新记录",
    memory: {
      eyebrow: "V1.1 · 显存占用",
      title: "通过 CPU 卸载降低显存",
      intro: "默认让模型常驻 GPU，优先保证推理速度。遇到显存不足时，可手动添加 --cpu-offload 重跑，将暂不工作的 DiT/VAE 权重放到主机内存，HuBERT 仅在提取音频特征时进入 GPU。程序不会自动判断显存、切换模式或在 OOM 后自动重试。",
      caption: "V1.1 进程显存峰值 · RTX PRO 5000 72GB",
      columns: ["模型", "默认 GPU 常驻", "添加 --cpu-offload"],
      scope: "512 × 512 · 15.04 秒音频 · 376 帧输出。采用 nvidia-smi 目标进程采样峰值，包含 CUDA 开销。两列均使用优化后的 V1.1 模型，比较的是两种显存模式；与论文中的 H20 速度测试分别记录。",
      cfgTitle: "为什么 Teacher 的显存占用更大？",
      cfg: "Teacher 与 Student 的参数数量和 BF16 权重规模相同。Teacher 同时计算三路 CFG，分支共享同一份权重，但需要更多中间张量和工作区；Student 只计算一路。本次测试中，常驻模式的峰值都由完整 VAE 解码主导；CPU 卸载后，峰值转到 DiT 去噪阶段，Teacher 的 CFG 显存开销才明显体现出来。采样步数主要影响耗时，不能按步数比例推算显存。",
      detailsTitle: "测试配置、主机内存与耗时",
      settings: "Teacher：30 步、参考/音频 CFG 2.5/10、sigma shift 5。Student：2 步、sigma shift 1、latent motion、默认首段 padding。CPU 卸载测试在 PyTorch 分配器 22 GiB 限额下完成。尚未在 RTX 4090 实机验证，也不保证任意长输入都能在 24 GiB 内运行；更长输入仍可能增加显存占用。",
      tradeoff: "Teacher 与 Student 的推理进程主机 RSS 峰值分别为 21.9 GiB 和 21.3 GiB，系统还需要额外内存。单次冷启动运行中，推理与写盘耗时：Teacher 从 563.6 秒变为 595.3 秒，Student 从 63.1 秒变为 82.1 秒；此处计时不含预处理、模型加载和进程启动。",
      validation: "两者全部 376 帧解码后视频及音频均与各自常驻模式结果完全一致，计算精度和采样参数保持不变。整卡采样峰值分别为 Teacher 19.83 GiB、Student 15.02 GiB；分配器 reserved 已包含 allocated，不应相加。",
      usage: "使用方法与显存说明",
    },
  },
};

window.UI_COPY.en.navUpdates = "V1.1 update";
window.UI_COPY.zh.navUpdates = "V1.1 更新";
